### your site title here

title: Alireza Kargar
description: Researcher | Mechatronics Engineer #| CAD Designer

baseurl: #name of GitHub repository
url: "https://alireza-kargar.github.io/" #custom url to be used instead of GitHub repository
email: alir3za.kargar@gmail.com #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: 
linkedin: "alireza-kargar-18923914b"
stackoverflow: 
github: "alireza-kargar"
researchgate: 
orcid: "0009-0006-3311-0443"
quora:
instagram: 
facebook:
googlescholar: "citations?user=kbts7oUAAAAJ&hl=en"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - CleanerBot.md
      - bams.md
      - NeuroLight.md
      - mmass.md
      - pBbot.md
      - HSRD.md
      - awnings.md
      - turbine.md
      

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
